<?php

namespace AppBundle\Repository;

/**
 * AccountPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
